baseURL = "/Musterdatenkatalog"
languageCode = "de-DE"
title = "Musterdatenkatalog Definitoonen"
uglyurls = true
disableKinds = ['taxonomy', 'term']

[outputs]
home = ['HTML']
page = ['HTML', 'rdf']

[mediaTypes]
[mediaTypes."application/rdf"]
suffixes = ["rdf"]

[outputFormats]
[outputFormats.rdf]
mediaType = 'application/rdf'
